version: "3"

services:
    mysql:
        image: mysql:latest
        restart: always
        ports:
            - 3306:3306
        volumes:
            - ${LEFT_DOCKER_PATH}/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: "test"
            MYSQL_USER: "admin"
            MYSQL_PASSWORD: "admin"
            MYSQL_ROOT_PASSWORD: "admin"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
