version: '2'

services:

    db_postgres:
        image: postgres:10.1
        restart: always
        ports:
            - 5432:5432
        volumes:
            - ${LEFT_DOCKER_PATH}/postgresql:/var/lib/postgresql
        environment:
            POSTGRES_USER: "root"
            POSTGRES_PASSWORD: "admin"
            POSTGRES_DB: "root"